synonyms_noun = {
    'resource': ['buffer', 'cache', 'core', 'thread', 'memory', ],  # noun
    'token': ['credential', 'token', 'certificate', 'password'],  # noun
    'optimization': ['cache', 'caching', 'optimization', 'optimizer',
                     'parallel', 'parallelism', 'compression', 'speedup',
                     'prefetch'],
    'update': ['update', 'backup', 'standby', 'replica', 'checkpoint', 'replication',
               'isolation', 'synchronization', 'sync',
               'flush', 'flushing'],  # noun
    # 'reliability': ['reliability', 'fail', 'failure', 'crash'],
    'function': ['function', 'functionality', 'feature', 'trace',
                 'log', 'logs', 'logging',
                 'monitor', 'monitoring',
                 'report', 'track', 'profiling', 'tracing'],
    'amount': ['amount', 'size', 'number', 'capacity'],
    'address': ['address', 'port', 'server', 'file', 'name', 'path', 'directory', 'dir',
                'endpoint', 'driver', 'location', 'host', 'where', 'id', 'gid', 'uid', 'userid',
                'hostname', 'domain', 'url', 'root', 'uri', 'place', 'position'],
    'parameter': ['parameter', 'option', 'variable', 'setting', 'configuration'],
    'time': ['second', 'millisecond', 'minute', 'hour', 'sec', 'nanosecond',
             'day', 'week', 'month', 'year',
             'duration', 'frequency', 'age', 'interval',
             'delay', 'expiration', 'period', 'lifetime', 'periodicity',
             'frequency'],
    'statistic': ['statistic', 'information', 'message', 'info', 'status'],
    'level': ['level', 'verbosity', 'granularity'],
    'performance': ['performance', 'effect', 'throughput', 'metric', 'speed', 'latency', 'bandwidth'],
    'security': ['security', 'ssl', 'tls', 'safety', 'authentication', 'authorization',
                 'verification', 'cors', 'auth', 'protection'],
    'encryption': ['encryption', 'decryption', 'cipher'],
    'quit': ['quitting'],
    'run': ['running'],
    'roll': ['rolling', 'rollover'],
    'start': ['beginning'],
    'record': ['recording'],
    'gather': ['gathering'],
    'plan': ['schedule'],
    'one': ['two', 'three', 'ten', 'hundred', 'thousand'],
    'member': ['membership'],
    'pause': ['sleep', 'stop'],
    'fail': ['failure', 'denial', 'problem', 'trouble', 'wrong', 'fault',
             'crashing', 'crash', 'defect', 'exception', 'violation', 'failover'],
    'expansion': ['expand'],
    'community': ['organization', 'association'],
    'monitor': ['observer', 'watcher'],
    'read': ['reading'],
    'write': ['writing'],
    'stab': ['stabs'],
    'admin': ['administrator', 'superuser', 'owner'],
    'explain': ['explanation'],
    'seek': ['exploration'],
    'policy': ['strategy', 'algorithm', 'method'],
    'dump': ['dumping'],
    'garbage': ['trash', 'junk'],
    'behavior': ['behaviour', 'misbehavior'],
    'provider': ['vendor'],
    'leak': ['leakage'],
    'length': ['width', 'height'],
    'trigger': ['triggering'],
    'audit': ['auditing'],
    'mail': ['email'],
    'document': ['documentation'],
    'report': ['reporting'],
    'bound': ['bounds'],
    'list': ['listing'],
    'substitution': ['replacement'],
    'wrap': ['wrapping', 'wraparound'],
    'convert': ['conversion'],
    'section': ['subsection'],
    'aggregate': ['aggregation'],
    'sample': ['sampling'],
    'component': ['element'],
    'deploy': ['deployment'],
    'loop': ['looping'],
    'clone': ['cloning'],
    'hash': ['hashing'],
    'partition': ['partitioning'],
    'decommission': ['decommissioning'],
    'upload': ['uploading'],
    'restart': ['restarting'],
    'resize': ['resizing'],
    'byte': ['bytes', 'GB', 'gb', 'kb', 'KB'],
    'checkpoint': ['savepoint', 'checkpointing'],
    'punctuation': ['comma', 'colon', 'semicolon', 'parenthesis', 'delimiter', 'backslash'],
    'malloc': ['realloc'],
    'node': ['namenode', 'datanode']
}

synonyms_verb = {
    'check': ['check', 'authenticate', 'validate', 'verify'],  # verb
    'optimize': ['optimize', 'parallel', 'improve', 'readahead', 'prefetch', 'parallelize',
                 'benefit', 'cache', 'preload', 'compress', 'speculate', 'balance'],  # verb
    'update': ['sync', 'update', 'commit', 'backup', 'synchronize', 'backup'],  # verb
    'function': ['profiling', 'scan', 'function', 'merge', 'track', 'insert'],  # verb
    'log': ['log', 'report', 'print', 'emit', 'display', 'output', 'document', 'logout'],
    'set': ['specify', 'set', 'control'],  # , 'use'
    'enable': ['enable', 'disable', 'toggle', 'allow', 'trigger'],
    'encrypt': ['encrypt', 'decrypt', 'crypt', 'crack'],
    'fail': ['fail', 'crash', 'hang', 'halt', 'stall', 'stop', 'shutdown', 'pause', 'die', 'abort'],
    'run': ['start', 'rerun', 'resume', 'restart', 'begin', 'perform'],
    'refuse': ['reject'],
    'advise': ['consult'],
    'explore': ['seek'],
    'increase': ['grow', 'decrease'],
    'replace': ['substitute'],
    'direct': ['guide'],
    'build': ['construct'],
    'control': ['configure', 'configured', 'reconfigure']
}

synonyms_adj_adv = {
    'better': ['better', 'faster', 'optimal', 'best', 'well', 'effectively', 'efficiently',
               'quick', 'quickly', 'fast', 'asynchronous', 'rapidly',
               'optionally', 'optimized', 'optimal', 'suboptimal', 'ideal',
               'effective', 'parallel', 'speculatively', 'balanced', 'ahead'],  # adj
    'secure': ['secure', 'safe', 'insecure', 'unsafe'],
    'first': ['1st', '2nd', '3rd', 'second', 'third', 'firstly', 'secondly', 'thirdly'],
    'single': ['double', 'triple', 'twice', 'half'],
    'forward': ['ahead', 'onwards', 'forwards', 'afterwards', 'subsequently', 'backward', 'backwards'],
    'early': ['late', 'soon'],
    'highly': ['significantly', 'notably', 'perfectly'],
    'consecutive': ['successive', 'following', ],
    'big': ['huge', 'giant', 'large'],
    'near': ['adjacent', 'nearby'],
}
